[package]
name = "earthwax"
version = "0.1.0"
edition = "2021"
default-run = "earthwax"


[dependencies]
ggez = "0.9.3"
clipboard-rs = "0.2.1"

[profile.dev]
opt-level = 0

[[bin]]
name = "crosshair" 
path = "tools/crosshair.rs" 

[[bin]]
name = "earthwax"
path = "src/main.rs"
